name: notes_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  bloc: ^9.1.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.12.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^9.1.1
  modal_progress_hud_nsn: ^0.5.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\Poppins-Regular.ttf
